Repository dsccommunity/ComputerManagementDsc, pull requests merged in 2018-10, with the labels that each got.

#185 ScheduledTask: Synchronize across time zone support
  CHANGELOG.md
  Modules/ComputerManagementDsc/DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1
  Modules/ComputerManagementDsc/DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.schema.mof
  Modules/ComputerManagementDsc/DSCResources/MSFT_ScheduledTask/en-US/MSFT_ScheduledTask.strings.psd1
  Modules/ComputerManagementDsc/Examples/Resources/ScheduledTask/15-CreateScheduledTaskOnceSynchronizeAcrossTimeZoneEnabled.ps1
  Tests/Integration/MSFT_ScheduledTask.Config.ps1
  Tests/Integration/MSFT_ScheduledTask.Integration.Tests.ps1
  Tests/Unit/MSFT_ScheduledTask.Tests.ps1
Labels: waiting for code fix

#190 Added .VSCode settings for applying DSC PSSA rules - Fixes #189
  .vscode/analyzersettings.psd1
  .vscode/settings.json
  CHANGELOG.md
Labels: needs review

#193 BREAKING CHANGE: PowerPlan: Add IsActive read-only property
  CHANGELOG.md
  Modules/ComputerManagementDsc/DSCResources/MSFT_PowerPlan/MSFT_PowerPlan.psm1
  Modules/ComputerManagementDsc/DSCResources/MSFT_PowerPlan/MSFT_PowerPlan.schema.mof
  Tests/Unit/MSFT_PowerPlan.Tests.ps1
Labels: breaking change, ready for merge
