Repository dsccommunity/ComputerManagementDsc, pull requests merged in 2019-09, with the labels that each got.

#256 [#255] Fixed type mismatch for MultipleInstances
  CHANGELOG.md
  DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1
Labels: waiting for code fix

#232 ScheduledTask: Better compatibility with Group LogonType using built-in groups
  CHANGELOG.md
  DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1
  Tests/Integration/MSFT_ScheduledTask.Config.ps1
  Tests/Integration/MSFT_ScheduledTask.Integration.Tests.ps1
Labels: waiting for author response

#259 Fix minor style issues in statement case
  CHANGELOG.md
  DSCResources/MSFT_ScheduledTask/MSFT_ScheduledTask.psm1
  DSCResources/MSFT_WindowsEventLog/MSFT_WindowsEventLog.psm1
Labels: needs review

#265 Fix minor style issues
  CHANGELOG.md
  DSCResources/MSFT_Computer/MSFT_Computer.psm1
  DSCResources/MSFT_OfflineDomainJoin/MSFT_OfflineDomainJoin.psm1
Labels: needs review

#261 New Resource: SmbServer
  CHANGELOG.md
  DSCResources/MSFT_SmbServerConfiguration/MSFT_SmbServerConfiguration.data.psd1
  DSCResources/MSFT_SmbServerConfiguration/MSFT_SmbServerConfiguration.psm1
  DSCResources/MSFT_SmbServerConfiguration/MSFT_SmbServerConfiguration.schema.mof
  DSCResources/MSFT_SmbServerConfiguration/README.md
  DSCResources/MSFT_SmbServerConfiguration/en-US/MSFT_SmbServerConfiguration.schema.mfl
  DSCResources/MSFT_SmbServerConfiguration/en-US/MSFT_SmbServerConfiguration.strings.psd1
  README.md
  Tests/Integration/MSFT_SmbServerConfiguration.Config.ps1
  Tests/Integration/MSFT_SmbServerConfiguration.Tests.ps1
  Tests/Unit/MSFT_SmbServerConfiguration.Tests.ps1
Labels: needs review

#274 Added missing examples for SMBServerConfiguration
  CHANGELOG.md
  Examples/Resources/SmbServerConfiguration/1-SmbServerConfiguration_AllProperties_Config.ps1
  Examples/Resources/SmbServerConfiguration/1-SmbServerConfiguration_DisableSmb1_Config.ps1
Labels: needs review
